"""add calories to weekly recipe.

Revision ID: 2fa615fb0380
Revises: bfe9e28dab87
Create Date: 2022-11-07 06:13:32.050001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa615fb0380'
down_revision = 'bfe9e28dab87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly__recipe', sa.Column('calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly__recipe', 'calories')
    # ### end Alembic commands ###
