"""added shopping recipe lable and new db

Revision ID: acc256bace82
Revises: ab78a20375b0
Create Date: 2022-09-29 15:18:40.231298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc256bace82'
down_revision = 'ab78a20375b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping', sa.Column('for_recipe', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping', 'for_recipe')
    # ### end Alembic commands ###
