"""added tags to recipe

Revision ID: b01519b25fae
Revises: 
Create Date: 2022-09-27 16:46:33.919113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01519b25fae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    op.add_column('recipe', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'tags')
    op.create_table('shopping_list',
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('aisle_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aisle_id'], ['aisle.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], )
    )
    # ### end Alembic commands ###
