"""added day tag to weekly recipe model

Revision ID: b8020ed5cce8
Revises: b01519b25fae
Create Date: 2022-09-28 05:03:27.777588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8020ed5cce8'
down_revision = 'b01519b25fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly__recipe', sa.Column('day', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly__recipe', 'day')
    # ### end Alembic commands ###
