"""added servings to weekly recipe

Revision ID: bfe9e28dab87
Revises: acc256bace82
Create Date: 2022-09-29 15:51:26.672839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe9e28dab87'
down_revision = 'acc256bace82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly__recipe', sa.Column('servings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly__recipe', 'servings')
    # ### end Alembic commands ###
